# Kubernetes file for hosting Medtype on the RENCI Sterling cluster

# Create a single Pod to run MedType. We don't need a full deployment of this,
# just something to run while we're doing stuff.
apiVersion: v1
kind: Pod
metadata:
  name: medtype-server
  labels:
    app: medtype-server
spec:
  restartPolicy: Never
  containers:
  - name: medtype-server
    image: ggvaidya/medtype-server
    ports:
    - containerPort: 8125
    resources:
      requests:
        memory: "8Gi"
        cpu: "0.5"
      limits:
        memory: "16Gi"
        cpu: "1"
---
# We would like to be able to access this port from within RENCI without making it public.
apiVersion: v1
kind: Service
metadata:
  name: medtype-hosting
spec:
  selector:
    app: medtype-server
  ports:
    - port: 8125
      protocol: TCP

